### ISSUE TITLE
Add icon and .desktop file

### ISSUE THREAD

**Issue by zxp19821005** [amphitheatre-app/desktop#3]
**Is your feature request related to a problem? Please describe.**
Maybe you can add and logo to the program,and add a `.desktop` file in the Linux package.

**Comment by wangeguo** [comment]
Thanks for the feedback! In my plan, executables and installers for the three major operating systems Linux, MacOS and Windows will be supported, such as: .deb, .rpm, .AppImage, .dmg, .pkg, .exe & installer.exe...

This requires an overall planning and design that includes:
1. determining the supported package formats;
2. technology selection for cross-platform compilation and packaging;
3. unification and reuse of resource directories, etc.;
4. the Github Actions workflow development;

The above requirements will be completed in multiple issues, so this issue is only one of them. Of course, you can also not consider so much, starting with support for Linux desktop icons.

If you are interested, please feel free to submit a Pull Request, or more development guidance/suggestions.
